**PERINTAH YANG ADA DI PPT**

In [38]:
bin_colors = {
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refused_color": "Red"
}

print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [39]:
bin_colors.get('approved_color')

'Green'

In [40]:
bin_colors.get('manual_color')

'Yellow'

In [41]:
bin_colors['approved_color'] = "Purple"
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


In [42]:
green = {'grass', 'leaves'}
print(green)

{'grass', 'leaves'}


In [43]:
green = {'grass', 'leaves', 'leaves'}
print(green)

{'grass', 'leaves'}


In [44]:
import pandas as pd
df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elena', 23, False],
    ['3', 'Steven', 40, True]
])

In [45]:
df.columns = ['id', 'name', 'age', 'decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [46]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [47]:
# Row selection
df.iloc[1:3, :]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [48]:
df[(df.age<35)&(df.decision==True)]

id   name  age  decision
0  1  Fares   32      True

In [50]:
import numpy as np
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [51]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [52]:
# Vektor Menggunakan list Python:
myVector = [22,33,44,55]
print(myVector)

[22, 33, 44, 55]


In [53]:
print(type(myVector))

<class 'list'>


In [54]:
# Menggunakan array numpy:
myVector = np.array([22,33,44,55])
print(myVector)

[22 33 44 55]


In [55]:
print(type(myVector))

<class 'numpy.ndarray'>


In [56]:
class Stack:
    def __init__(self):
        self.items = []

    def isEmpty(self):
        return self.items == []

    def push(self, item):
        self.items.append(item)

    def pop(self):
        return self.items.pop()

    def peek(self):
        return self.items[len(self.items)-1]

    def size(self):
        return len(self.items)

In [57]:
stack=Stack()
stack.push('Red')
stack.push('Green')
stack.push('Blue')
stack.push("Yellow")
stack.pop()
stack.isEmpty()

False

In [58]:
class Queue(object):
    def __init__(self):
        self.items = []

    def isEmpty(self):
        return self.items == []

    def enqueue(self, item):
        self.items.insert(0, item)

    def dequeue(self):
        return self.items.pop()

    def size(self):
        return len(self.items)

queue = Queue()
queue.enqueue('Red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')

In [59]:
print(queue.size())
print(queue.dequeue())
print(queue.dequeue())

4
Red
Green


**LATIHAN DALAM KELAS**

In [1]:
alist=["John", 33, "Toronto", True]
print(alist)


['John', 33, 'Toronto', True]


In [23]:
import datetime as dt
tanggal = dt.date.today()
Mahasiswa = ['Teesa', '2023071062', 'informatika', 'DAA', str(tanggal), 'UPJ']
print(Mahasiswa)

['Teesa', '2023071062', 'informatika', 'DAA', '2024-09-20', 'UPJ']


In [6]:
print (alist [3])

True


In [7]:
print (Mahasiswa [2])

informatika


In [9]:
#memamggil urutan indeks mahasiswa

print ("NIM" , Mahasiswa[1])

NIM 2023071062


In [10]:
print ("Kampus", Mahasiswa[5])

Kampus UPJ


In [11]:
bin_colors = ['red', 'green','blue','yellow']
bin_colors [0:2]

['red', 'green']

In [12]:
bin_colors[1:2]
#

['green']

In [13]:
bin_colors[2:2]

[]

In [18]:
print ("Nim dan Prodi: ", Mahasiswa[1:3])

Nim dan Prodi:  ['2023071062', 'informatika']


In [20]:
bin_colors = ['red', 'green','blue','yellow']
for acolor in bin_colors:
    print(acolor + " square")

red square
green square
blue square
yellow square


In [24]:
for aMahasiswa in Mahasiswa:
    print (aMahasiswa + " UPJ")

Teesa UPJ
2023071062 UPJ
informatika UPJ
DAA UPJ
2024-09-20 UPJ
UPJ UPJ


In [27]:
bin_colors[2]

'blue'

In [28]:
bin_colors[2:]

['blue', 'yellow']

In [30]:
UPJ = ("Universitas", "Pembangunan", "Jaya")


In [33]:
print(UPJ)


('Universitas', 'Pembangunan', 'Jaya')


In [34]:
print(UPJ[0])


Universitas


In [35]:
print(UPJ[2])


Jaya


In [36]:
print(UPJ[1:])


('Pembangunan', 'Jaya')


In [60]:
print (nested_tuple)

(100, (200, 400, 600), 300, (400, 800))


**HAL16**

In [37]:
nested_tuple = (100, (200, 400, 600), 300, (400, 800))


**HAL 20**

In [61]:
mhs_dict = {
    "Nama": "Teesa",
    "NIM": "2023071062",
    "Prodi": "Informatika",
    "Universitas": "Universitas Pembangunan Jaya"
}
print(mhs_dict)

{'Nama': 'Teesa', 'NIM': '2023071062', 'Prodi': 'Informatika', 'Universitas': 'Universitas Pembangunan Jaya'}


**HAL 23**

In [65]:
# Define two sets
yellow = {'dandelions', 'fire hydrant', 'leaves'}
red = {'blood', 'rose', 'fire hydrant', 'leaves'}



In [66]:
# Union (yellow OR red)
yellow_or_red = yellow | red
print(yellow_or_red)



{'blood', 'fire hydrant', 'rose', 'dandelions', 'leaves'}


In [67]:
# Intersection (yellow AND red)
yellow_and_red = yellow & red
print(yellow_and_red)


{'fire hydrant', 'leaves'}


**HAL 28**

In [63]:
import pandas as pd

data = {
    "No": [1, 2, 3],
    "Prodi": ["Informatika", "Sistem Informasi", "Teknik Sipil"],
    "Mahasiswa": [50, 55, 40],
    "Lakilaki": [30, 30, 30],
    "Perempuan": [20, 25, 10]
}
mhs = pd.DataFrame(data)
print(mhs)



   No             Prodi  Mahasiswa  Lakilaki  Perempuan
0   1       Informatika         50        30         20
1   2  Sistem Informasi         55        30         25
2   3        Arsitektur         40        30         10


In [68]:
import pandas as pd

data = {
    "No": [1, 2, 3],
    "Prodi": ["INF", "SIF", "TM"],
    "Mahasiswa": [50, 55, 45],
    "Lakilaki": [30, 30, 35],
    "Perempuan": [20, 25, 10]
}
mhs = pd.DataFrame(data)
print(mhs)



   No Prodi  Mahasiswa  Lakilaki  Perempuan
0   1   INF         50        30         20
1   2   SIF         55        30         25
2   3    TM         45        35         10


**HAL 30**

In [64]:
import numpy as np
matrix = np.array([[100, 200, 300], [700, 600, 500], [900, 1000, 800]])
transpose_matrix = matrix.T
print(transpose_matrix)

[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


**TUGAS TAMBAHAN**

In [71]:
# Define the original matrix
matrix = [[100, 200, 300],
          [700, 600, 500],
          [900, 1000, 800]]

# Transpose matrix manual
transpose_matrix = [[matrix[j][i] for j in range(len(matrix))] for i in range(len(matrix[0]))]

# Print transposed matrix
for row in transpose_matrix:
    print(row)


[100, 700, 900]
[200, 600, 1000]
[300, 500, 800]
